version: 0.2
phases:
  pre_build:
    commands:
      - echo "Meu pre build da aplicação"
  build:
    commands:
      - echo "Testing"
      - mvn clean test
      - echo "Building"
      - mvn clean compile package
  post_build:
    commands:
      - echo "Movendo os arquivos que serão feitos upload"
      - mv target/*.war ./ROOT.war
artifacts:
  files:
    - ROOT.war